name: territory_run
description: A GPS fitness game where players claim real-world territory by running outdoors.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.7.15
  google_sign_in: ^6.2.1

  # Sensors & Anti-Cheat
  sensors_plus: ^4.0.2
  pedometer: ^4.0.2

  # State Management
  provider: ^6.1.1

  # Offline / Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3
  workmanager: ^0.5.2
  path_provider: ^2.1.2

  # UI
  fl_chart: ^0.66.2
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # Utilities
  uuid: ^4.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/map_style.json
    - assets/images/

