import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '../models/user_model.dart';
import '../models/run_model.dart';
import '../models/territory_model.dart';
import '../models/district_model.dart';
import '../models/sync_queue_item.dart';

/// Local Hive database manager — the single source of truth for offline-first reads.
class OfflineStorageService {
  OfflineStorageService();

  static const String _runsBox = 'runs';
  static const String _territoriesBox = 'territories';
  static const String _districtsBox = 'districts';
  static const String _userBox = 'user';
  static const String _syncQueueBox = 'sync_queue';
  static const String _settingsBox = 'settings';

  bool _initialized = false;

  /// Initialize Hive and open all boxes.
  Future<void> initialize() async {
    if (_initialized) return;

    await Hive.initFlutter();

    // Register adapters (generated by hive_generator).
    // In production these are auto-generated .g.dart files.
    // Hive.registerAdapter(UserModelAdapter());
    // Hive.registerAdapter(RunModelAdapter());
    // Hive.registerAdapter(TerritoryModelAdapter());
    // Hive.registerAdapter(DistrictModelAdapter());
    // Hive.registerAdapter(SyncQueueItemAdapter());
    // Hive.registerAdapter(SyncActionAdapter());
    // Hive.registerAdapter(BattleResultAdapter());

    await Future.wait([
      Hive.openBox<Map>(_runsBox),
      Hive.openBox<Map>(_territoriesBox),
      Hive.openBox<Map>(_districtsBox),
      Hive.openBox<Map>(_userBox),
      Hive.openBox<Map>(_syncQueueBox),
      Hive.openBox(_settingsBox),
    ]);

    _initialized = true;
    debugPrint('[OfflineStorage] Initialized all Hive boxes');
  }

  // ── Runs ────────────────────────────────────────────────

  Future<void> saveRun(RunModel run) async {
    final box = Hive.box<Map>(_runsBox);
    await box.put(run.id, run.toJson());
  }

  List<RunModel> getAllRuns() {
    final box = Hive.box<Map>(_runsBox);
    return box.values
        .map((json) => RunModel.fromJson(Map<String, dynamic>.from(json)))
        .toList()
      ..sort((a, b) => b.startTime.compareTo(a.startTime));
  }

  List<RunModel> getUnsyncedRuns() {
    return getAllRuns().where((r) => !r.synced).toList();
  }

  Future<void> markRunSynced(String runId) async {
    final box = Hive.box<Map>(_runsBox);
    final json = box.get(runId);
    if (json != null) {
      final map = Map<String, dynamic>.from(json);
      map['synced'] = true;
      await box.put(runId, map);
    }
  }

  // ── Territories ─────────────────────────────────────────

  Future<void> saveTerritory(TerritoryModel territory) async {
    final box = Hive.box<Map>(_territoriesBox);
    await box.put(territory.id, territory.toJson());
  }

  Future<void> saveTerritories(List<TerritoryModel> territories) async {
    final box = Hive.box<Map>(_territoriesBox);
    final entries = {for (var t in territories) t.id: t.toJson()};
    await box.putAll(entries);
  }

  List<TerritoryModel> getAllTerritories() {
    final box = Hive.box<Map>(_territoriesBox);
    return box.values
        .map((json) =>
            TerritoryModel.fromJson(Map<String, dynamic>.from(json)))
        .toList();
  }

  Future<void> removeTerritory(String id) async {
    final box = Hive.box<Map>(_territoriesBox);
    await box.delete(id);
  }

  // ── Districts ───────────────────────────────────────────

  Future<void> saveDistrict(DistrictModel district) async {
    final box = Hive.box<Map>(_districtsBox);
    await box.put(district.id, district.toJson());
  }

  List<DistrictModel> getAllDistricts() {
    final box = Hive.box<Map>(_districtsBox);
    return box.values
        .map((json) =>
            DistrictModel.fromJson(Map<String, dynamic>.from(json)))
        .toList();
  }

  // ── User Profile ────────────────────────────────────────

  Future<void> saveUser(UserModel user) async {
    final box = Hive.box<Map>(_userBox);
    await box.put('current', user.toJson());
  }

  UserModel? getCurrentUser() {
    final box = Hive.box<Map>(_userBox);
    final json = box.get('current');
    if (json == null) return null;
    return UserModel.fromJson(Map<String, dynamic>.from(json));
  }

  // ── Sync Queue ──────────────────────────────────────────

  Future<void> enqueue(SyncQueueItem item) async {
    final box = Hive.box<Map>(_syncQueueBox);
    await box.put(item.id, {
      'id': item.id,
      'action': item.action.name,
      'collection': item.collection,
      'document_id': item.documentId,
      'data': item.data,
      'created_at': item.createdAt.toIso8601String(),
      'retry_count': item.retryCount,
    });
  }

  List<SyncQueueItem> getPendingQueue() {
    final box = Hive.box<Map>(_syncQueueBox);
    return box.values.map((json) {
      final map = Map<String, dynamic>.from(json);
      return SyncQueueItem(
        id: map['id'] as String,
        action: SyncAction.values.firstWhere((e) => e.name == map['action']),
        collection: map['collection'] as String,
        documentId: map['document_id'] as String,
        data: Map<String, dynamic>.from(map['data'] as Map),
        createdAt: DateTime.parse(map['created_at'] as String),
        retryCount: map['retry_count'] as int? ?? 0,
      );
    }).toList()
      ..sort((a, b) => a.createdAt.compareTo(b.createdAt));
  }

  int get pendingQueueCount => Hive.box<Map>(_syncQueueBox).length;

  Future<void> removeFromQueue(String id) async {
    final box = Hive.box<Map>(_syncQueueBox);
    await box.delete(id);
  }

  Future<void> clearQueue() async {
    final box = Hive.box<Map>(_syncQueueBox);
    await box.clear();
  }

  // ── Settings ────────────────────────────────────────────

  Future<void> setSetting(String key, dynamic value) async {
    final box = Hive.box(_settingsBox);
    await box.put(key, value);
  }

  T? getSetting<T>(String key) {
    final box = Hive.box(_settingsBox);
    return box.get(key) as T?;
  }

  // ── Cleanup ─────────────────────────────────────────────

  Future<void> clearAll() async {
    await Future.wait([
      Hive.box<Map>(_runsBox).clear(),
      Hive.box<Map>(_territoriesBox).clear(),
      Hive.box<Map>(_districtsBox).clear(),
      Hive.box<Map>(_userBox).clear(),
      Hive.box<Map>(_syncQueueBox).clear(),
      Hive.box(_settingsBox).clear(),
    ]);
  }
}
