// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAduKb2oaDz-Lt2nRbWYKIgliOBwDEb9lk',
    appId: '1:73156686796:android:6ee980d7ac80dc3367a369',
    messagingSenderId: '73156686796',
    projectId: 'terr-app-e7dfb',
    storageBucket: 'terr-app-e7dfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClscVYuCRJyWCLOhHFDF0XNSp-RcGQd3o',
    appId: '1:73156686796:ios:0bd4ee59b72a2cae67a369',
    messagingSenderId: '73156686796',
    projectId: 'terr-app-e7dfb',
    storageBucket: 'terr-app-e7dfb.firebasestorage.app',
    iosBundleId: 'com.territoryrun.territoryRun',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCukW_qNvPy-QbqrgCB-dxo2lJbzxqL5rA',
    appId: '1:73156686796:web:5eda2ba7ceb012b667a369',
    messagingSenderId: '73156686796',
    projectId: 'terr-app-e7dfb',
    authDomain: 'terr-app-e7dfb.firebaseapp.com',
    storageBucket: 'terr-app-e7dfb.firebasestorage.app',
    measurementId: 'G-0TPHNKQLLD',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCukW_qNvPy-QbqrgCB-dxo2lJbzxqL5rA',
    appId: '1:73156686796:web:d374e51e05df618767a369',
    messagingSenderId: '73156686796',
    projectId: 'terr-app-e7dfb',
    authDomain: 'terr-app-e7dfb.firebaseapp.com',
    storageBucket: 'terr-app-e7dfb.firebasestorage.app',
    measurementId: 'G-45L7VG2C2D',
  );

}